### ISSUE TITLE
donate page height set to 100% resulting in being 100% the size of the parent not the viewport

### ISSUE THREAD

**Issue by CameronGr** [Delta-Simulations/Delta-Simulations.github.io#1]
worse at higher resolutions, 
![](https://cdn.discordapp.com/attachments/897975504815149127/1151805409347244133/image.png)
to fix it just change
`height: 100% ;` to `height: 100vh;` found here:
https://github.com/Delta-Simulations/Delta-Simulations.github.io/blob/63d2cb7ec698198ef4d1d6e880a70bc1fd18f17e/style.css#L54

**Comment by Destroyer121** [comment]
Fixed in refactor
